### ISSUE TITLE
Inconsistent advice in exersice 1 markdown

### ISSUE THREAD

**Issue by hansaskov** [jakobhviid/BigDataCourseExercises#7]
At one point in exercise 1 you give a task to create our pods within a stackable namespace 
https://github.com/jakobhviid/BigDataCourseExercises/blob/main/lectures/02/exercises.md?plain=1#L18-L20

But in another part of exercise 1 it is said we need to create the hdfs cluster within another namespace
https://github.com/jakobhviid/BigDataCourseExercises/blob/main/lectures/02/exercises.md?plain=1#L42

**Comment by anderslaunerbaek** [comment]
Hi Hans Askov,

Thanks for opening an issue and to provide feedback. I do not have a fixed opinion of how to use namespaces in Kubernetes. However, one approach for using (different) namespaces is to isolate identical resources. In other words, avoid having a cluttered environment. Please look into further documentation about namespaces [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/).

> In Kubernetes, namespaces provides a mechanism for isolating groups of resources within a single cluster. 
> [ref: Kubernetes - Namespaces](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/)

In order to follow up on your claim of inconsistent advice my repose would be one can argue it makes sense to isolate stackable operators inside one namespace since these are "common logic" for more than the HDFS service. Later on, we might use other stackable operators to deploy Apache Spark.

/Anders

**Comment by anderslaunerbaek** [comment]
This issue is to be closed due to inactivity.
